version: "3"

services:
  db:
    image: postgres
    ports:
    - 5433:5432
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    - "postgres:/var/lib/postgresql/data"

volumes:
  postgres: